version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "4201:4200"
    depends_on:
      - backend

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "root"
    volumes:
      - ./backend/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql  # Persistent volume for MySQL data
    ports:
      - "3307:3306"

volumes:
  mysql_data:   # Declare the volume
